### ISSUE TITLE
No module named 'image_utils'

### ISSUE THREAD

**Issue by ml-boringtao** [bstriner/keras-adversarial#16]
Hi,

I m using Python 3.5.2, Keras 2, Pillow 4.1. When I run 'from image_utils import...'. It shows 'No module named 'image_utils''. I cannot find any answers on the net. Can you help out?

Thanks
Tao

**Comment by ml-boringtao** [comment]
I found it. cheers.

**Comment by cyberlife-inside** [comment]
I have the same problem.
I have installed the keras-aadversarial module and i am having the same problems ?
how did you solved it ?

regards

**Comment by bstriner** [comment]
Hi @langju ! `image_utils` is a file in the examples directory. I put it there instead of in the module itself because it is just the code for printing the example images and kind of tangential to the module.

If `.` is on your python path, python will be able to find modules in the current directory. If that isn't the default, you could do something like `PYTHONPATH=.:$PYTHONPATH python ...`.

If you add these lines to the python file before the `import` it will also fix it:

```
import sys
import os
sys.path.insert(0,os.dirname(__file__))
```

Cheers

**Comment by bstriner** [comment]
Alternatively, add `.` to your python path in your system, and you can handle similarly structured code. Otherwise, there is no way to run multiple files without installing them as modules.
